[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cocotb>=2.0.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pytest>=9.0.0",
    "pyuvm>=4.0.1",
    "scipy>=1.16.3",
]
